---
title: "Databases"
author: ["Kirill & Nicolas", "cynkra GmbH"]
date: "March 15, 2022"
output:
  cynkradown::cynkra_slides:
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
    seal: true
lang: english
font: frutiger
wide: false
colorlinks: false
logo: true
---

<style type="text/css">
.pull-left {
  margin-top: -25px;
}
.pull-right {
  margin-top: -25px;
}
.remark-code {
    font-size: 14px;
}
.font17 {
    font-size: 17px;
}
.font14 {
    font-size: 14px;
}
</style>


```{r databases-2-1, include = FALSE}
knitr::opts_chunk$set(cache = TRUE, comment = "")

library(tidyverse)
library(DBI)
library(dm)

options(width = 68)

options(pillar.bold = TRUE)
options(cli.num_colors = 256)

fansi::set_knit_hooks(knitr::knit_hooks, c("output", "message", "warning", "error"))
```

```{r databases-2-2, results='hide', message=FALSE, cache = FALSE}
con_duckdb <- dbConnect(duckdb::duckdb())
con_duckdb
```

```{r databases-2-3, cache = FALSE}
dm::copy_dm_to(
  con_duckdb,
  dm::dm_pixarfilms(),
  set_key_constraints = FALSE,
  temporary = FALSE
)
```

```{r databases-2-4, cache = FALSE}
pixar_films <- tbl(con_duckdb, "pixar_films")
pixar_films
```

```{r databases-2-5, cache = FALSE}
con_sqlite <- DBI::dbConnect(RSQLite::SQLite(), extended_types = TRUE)
dm::copy_dm_to(
  con_sqlite,
  dm::dm_pixarfilms(),
  set_key_constraints = FALSE,
  temporary = FALSE
)
```

```{r databases-2-6, cache = FALSE}
pixar_films_sqlite <- tbl(con_sqlite, "pixar_films")
pixar_films_sqlite
```
